### ISSUE TITLE
center support

### ISSUE THREAD

**Issue by neeasade** [wallyqs/org-ruby#93]
eg:

```
#+begin_center
this text should be centered
#+end_center
```

**Comment by melioratus** [comment]
I am not able to reproduce this issue. Please provide more information

**Comment by neeasade** [comment]
hmm trying to remember why I filed this (I see that there IS center support in this repo)

IIRC I came here because I was wanting github's org rendering for org to support it ([gist example](https://gist.github.com/neeasade/b21ce60252cd17731729866c82f92c39)), and that led me to this library

might be the wrong place to request it, feel free to close

**Comment by maxnikulin** [comment]
org-ruby certainly supports centering:
```
org-ruby -t html <(printf "#+begin_center\ntext\n#+end_center")
<div style="text-align: center">
  <p>text</p>
</div>
```
The issue is that GitHub strips `class` and `style` HTML attributes.

A workaround is to use the deprecated `align` attribute allowed in the sanitizer config:
```html
<p align="center">text</p>
```
I had a hope that GitHub renderer may be configured with custom markup (`-m` in the case of CLI tool). I tried the following, but got the attribute for the closing tag as well
```yaml
:HtmlBlockTag:
  :center: div align="center"
```
```html
<div align="center" style="text-align: center">
  <p>text</p>
</div align="center">
```
Have I missed something or custom markup is not flexible enough?

**Comment by neeasade** [comment]
yeah that provides plenty of workaround -- thanks! closing

**Comment by maxnikulin** [comment]
I would leave this issue open since I do not see a way to create an Org mode file compatible with the native `ox-html` exporter and that can be properly rendered on GitHub.

I can not reopen the issue since I am neither maintainer nor reporter.

The following is not a workaround since `<center>` tags are stripped by the GitHub HTML sanitizer:
```yaml
:HtmlBlockTag:
  :center: center
```
for `-m` argument. Not to mention that this tag is deprecated as well.

From my point of view, this issue may be considered as a feature request to implement configurable attributes for customized tags.

As a hack, it should be easy to strip for closing tag everything after element name
```
:HtmlBlockTag:
  :center: div align="center"
```
however last commit in this repository was 4 years ago. I have noticed commits fixing some issues in https://github.com/ricardoricho/org-ruby/, but I am not sure concerning status of that repository.

**Comment by neeasade** [comment]
For future searchers: I was able to do what I wanted by referencing the examples here: https://github.com/noncog/github-org-mode-hacks
